### ISSUE TITLE
crashes on mac and rpi : Bad file descriptor

### ISSUE THREAD

**Issue by gepatto** [BowlerHatLLC/snake-server#1]
I have Snake-server  (1.0.1) crashes on macos and raspberrypi.

```
/Users/user/Documents/Development/haxe/lib/snake-server/1,1,0/src/snake/socket/BaseServer.hx:61: characters 4-9 : Uncaught exception Bad file descriptor(getsockname, )
/Users/user/Documents/Development/haxe/lib/snake-server/1,1,0/src/snake/Run.hx:74: characters 3-28 : Called from here
```
I also see messages like
`Thread 127 killed on uncaught exception Unix.Unix_error(3, "recv", "")`

and 
`Thread 86 killed on uncaught exception Unix.Unix_error(3, "select", "")`

Sometimes everything loads, but most of the times it will the produce the crash immediately or after a couple of reloads of the webpage

tested with openfl PiratePig sample and some flixel-samples

**Comment by joshtynjala** [comment]
Are you simply running `haxelib run snake-server`, or are you specifying any options?

**Comment by gepatto** [comment]
Just that. No other options

**Comment by joshtynjala** [comment]
I spent the first half of today being able to reproduce this issue (on macOS) only if I click the reload button in my browser many times extremely fast. However, with no changes to my code, it now seems to be happening almost every time that I reload, even if I wait some time to reload. I'm not sure why it has behaved differently at different times today. It's very strange.

However, when I build for Neko, it seems to be much more stable. It seems to be able to catch exceptions that the Haxe interpreter cannot.

I'm also seeing more stable behavior in both the interpreter and Neko when I disable threading.

I will need to investigate more.

**Comment by joshtynjala** [comment]
@gepatto Can you try updating to snake-server 1.2? I suspect that it will be a bit more stable. Thanks!

**Comment by gepatto** [comment]
Yes, all ok now on both mac and pi. 
Crashes seem to be gone.
